"use strict";
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<e.length-1;g++){var f=e[g];if(!(f in d))return;d=d[f]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),d=c.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(d.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(c){return{value:c,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(d){return a.next(d)}function c(d){return a["throw"](d)}return new Promise(function(d,e){function g(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(g,e)}g(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(e,g){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:g})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(e){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.polyfill("Symbol.asyncIterator",function(a){return a?a:Symbol("Symbol.asyncIterator")},"es9","es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.makeAsyncIterator=function(a){var b=a[Symbol.asyncIterator];return void 0!==b?b.call(a):new $jscomp.AsyncIteratorFromSyncWrapper($jscomp.makeIterator(a))};
$jscomp.AsyncIteratorFromSyncWrapper=function(a){this[Symbol.asyncIterator]=function(){return this};this[Symbol.iterator]=function(){return a};this.next=function(b){return Promise.resolve(a.next(b))};void 0!==a["throw"]&&(this["throw"]=function(b){return Promise.resolve(a["throw"](b))});void 0!==a["return"]&&(this["return"]=function(b){return Promise.resolve(a["return"](b))})};var addButton=document.getElementById("addButton"),listView=document.getElementById("listView"),scrollBar=document.getElementById("scrollBar");
addButton.addEventListener("click",function(){var a=document.createElement("div");a.classList.add("AddTitleView");var b=document.createElement("input");b.type="text";b.placeholder="Titel suchen";b.autofocus=!0;a.appendChild(b);var c=document.createElement("ul");c.classList.add("searchResults");a.appendChild(c);var d;b.oninput=function(){c.innerHTML="";d&&clearTimeout(d);d=window.setTimeout(function(){0<b.value.length&&httpGet("https://api.themoviedb.org/3/search/multi?api_key="+api.tmdb+"&language=de&query="+
encodeURIComponent(b.value)+"&include_adult=true&region=de").then(function(g){var f=JSON.parse(g);if(0<f.results.length)for(g=$jscomp.makeIterator(f.results),f=g.next();!f.done;f=g.next()){if(f=f.value,"movie"===f.media_type||"tv"===f.media_type){cache.tmdb.set(f.id,f);var h=document.createElement("li"),k=cache.img(getPosterUrlBypath(f.poster_path));h.appendChild(k);k=document.createElement("span");k.innerHTML="<b>"+(f.title?f.title:f.name)+"</b>";h.appendChild(k);h.setAttribute("onclick","database.movies.add("+
f.id.toString()+');anim.popup.close("addMovieDialog");');c.appendChild(h)}}else console.error("Something went wrong\n\n"+g)})},750)};var e=document.createElement("div");e.classList.add("blur");e.appendChild(a);e.id="addMovieDialog";e.addEventListener("click",function(g){g.target&&"addMovieDialog"===g.target.id&&anim.popup.close("addMovieDialog")});document.body.appendChild(e);a.focus()});
var anim={popup:{close:function(a){var b=document.getElementById(a);b&&(b.style.transition="all 200ms ease-in-out",b.style.setProperty("backdrop-filter","blur(0) saturate(1)"),a=b.firstElementChild,a.style.transition="all 200ms ease-in-out",a.style.transform="translateY(50vh)",setTimeout(function(){b&&b.remove()},200))}},movieList:{shouldBeClosed:"",open:function(a){var b=document.getElementById(a);if(b){var c=document.getElementById(this.shouldBeClosed);c&&c.classList.remove("open");b.classList.add("open");
this.shouldBeClosed=a}},close:function(a){var b=document.getElementById(a);b&&(b.classList.remove("open"),b.scrollIntoView({behavior:"smooth",block:"center",inline:"nearest"}),this.shouldBeClosed===a&&(this.shouldBeClosed=""))}}},api={tmdb:"3f43edeb84d241b315fe4a921bb9b74a"},cache={tmdb:new Map,imgList:new Map,img:function(a){if(this.imgList.has(a))return this.imgList.get(a);var b=document.createElement("img");b.src=a;this.imgList.set(a,b);return b},lastScrollLetter:"\x00"},version=3,Movie=function(a){this.cover=
getPosterUrlBypath(a.poster_path);this.title=a.title?a.title:a.name?a.name:"";this.info=a.overview;this.adult=!0===a.adult;this.genres=[];for(var b=$jscomp.makeIterator(a.genre_ids),c=b.next();!c.done;c=b.next())c=c.value,genreIDs.has(c)&&this.genres.push(genreIDs.get(c));this.id=a.id},dbStoreNames;(function(a){a.shelf="shelf";a.wishlist="wishlist"})(dbStoreNames||(dbStoreNames={}));
var database={idb:indexedDB.open("library",version),dbRef:null,loadFullDB:function(){if(this.dbRef){var a=this.dbRef.transaction(dbStoreNames.shelf,"readonly").objectStore(dbStoreNames.shelf).openCursor();a&&(a.onsuccess=function(b){if(b=b.target.result)database.movies.storage.push(b.value),movieList.update(),b["continue"]()})}},addToShelf:function(a){if(this.dbRef){var b=this.dbRef.transaction(dbStoreNames.shelf,"readwrite");b.onerror=function(c){alert(c.target.error);console.error(c)};b.objectStore(dbStoreNames.shelf).add(a)}},
addToWishList:function(a){if(this.dbRef){var b=this.dbRef.transaction(dbStoreNames.wishlist,"readwrite");b.onerror=function(c){alert(c.target.error);console.error(c)};b.objectStore(dbStoreNames.wishlist).add(a)}},wishlist:indexedDB.open(dbStoreNames.shelf,version),movies:{storage:[],add:function(a){if(cache.tmdb.has(a)){var b=new Movie(cache.tmdb.get(a));database.addToShelf(b);this.storage.push(b);movieList.update();setTimeout(function(){document.getElementById("M"+a.toString()).scrollIntoView({behavior:"smooth",
block:"center",inline:"nearest"})},500)}}}};database.idb.onupgradeneeded=function(a){var b=a.target;b&&(database.dbRef=b.result,database.dbRef.createObjectStore(dbStoreNames.shelf,{keyPath:"id"}),database.dbRef.createObjectStore(dbStoreNames.wishlist,{keyPath:"id"}));console.debug(a)};database.idb.onsuccess=function(a){var b=a.target;b&&(database.dbRef=b.result);console.debug(a);database.loadFullDB()};database.idb.onerror=function(a){console.error(a)};
function httpGet(a){return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){return b["return"](new Promise(function(c){var d=new XMLHttpRequest;d.onreadystatechange=function(){4==d.readyState&&(200==d.status?c(d.responseText):console.error(d.response))};d.open("GET",a,!0);d.send(null)}))})}
var movieList={update:function(){database.movies.storage.sort(function(k,l){var m=k.title.toLowerCase(),n=l.title.toLowerCase();return m>n?1:m<n?-1:0});for(var a="",b=[],c=$jscomp.makeIterator(database.movies.storage),d=c.next();!d.done;d=c.next()){d=d.value;var e=d.title[0].toUpperCase();if(0===b.length||b[b.length-1]!==e){b.push(e);var g=document.createElement("li");g.classList.add("letter");g.id="letter"+e;g.innerText=e;a+=g.outerHTML}e=document.createElement("li");e.classList.add("movie");e.id=
"M"+d.id.toString();g=JSON.stringify(e.id);var f=document.createElement("section"),h=document.createElement("img");h.src=d.cover;h.classList.add("cover");f.appendChild(h);h=document.createElement("span");h.classList.add("title");h.innerText=d.title;f.setAttribute("onclick","anim.movieList.open("+g+")");f.appendChild(h);e.appendChild(f);d.adult&&(f=document.createElement("span"),f.innerText="18+",f.classList.add("adult"),e.appendChild(f));f=document.createElement("p");f.classList.add("info");f.innerText=
d.info;e.appendChild(f);d.genres&&0<d.genres.length&&(f=document.createElement("p"),f.classList.add("genres"),f.innerText="Genres: "+d.genres.join(", "),e.appendChild(f));d=document.createElement("img");d.src="img/back.svg";d.setAttribute("onclick","anim.movieList.close("+g+")");d.classList.add("closeBtn");e.appendChild(d);a+=e.outerHTML}listView.innerHTML=a;a="";c=$jscomp.makeIterator(b);for(d=c.next();!d.done;d=c.next())d=d.value,e=document.createElement("li"),e.innerText=d,e.style.height=Math.round(99/
b.length)+"%",a+=e.outerHTML;scrollBar.innerHTML=a}};document.body.addEventListener("contextmenu",function(a){a.preventDefault();return!1});
function scrollBarUpdate(a){var b,c,d,e,g,f,h,k,l,m;return $jscomp.asyncExecutePromiseGeneratorProgram(function(n){b=(a instanceof TouchEvent?a.changedTouches[0].clientY:a.clientY)/window.innerHeight;c=void 0;d=-1;e=$jscomp.makeIterator(scrollBar.childNodes);for(g=e.next();!g.done;g=e.next())h=f=g.value,k=h.getBoundingClientRect(),l=1-Math.abs(k.top/window.innerHeight-b),l>d&&(d=l,c=h.innerText),h.style.color="white",h.style.setProperty("--pos-x","-"+Math.floor(Math.pow(100,l)).toString()+"px"),h.style.setProperty("color",
"rgba(255,255,255, "+(Math.pow(25,l)/25).toFixed(2).toString()+")");c&&cache.lastScrollLetter!==c&&(cache.lastScrollLetter=c,(m=document.getElementById("letter"+c))&&m.scrollIntoView({behavior:"smooth",block:"start"}));n.jumpToEnd()})}addEventListener("touchstart",function(a){return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){a.target!==scrollBar&&a.target.parentNode!==scrollBar||addEventListener("touchmove",scrollBarUpdate);b.jumpToEnd()})});
addEventListener("touchend",function(){var a,b,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){1==d.nextAddress&&(removeEventListener("touchmove",scrollBarUpdate),a=$jscomp.makeAsyncIterator(scrollBar.childNodes));if(5!=d.nextAddress)return d.yield(a.next(),5);b=d.yieldResult;if(b.done)return d.jumpTo(0);c=b.value;c.style.color="transparent";c.style.setProperty("--pos-x","0");return d.jumpTo(2)})});
var getPosterUrlBypath=function(a,b){return a?"https://image.tmdb.org/t/p/"+(void 0===b?"w500":b)+a:"img/popcorn.webp"},genreIDs=new Map([[28,"Action"],[12,"Adventure"],[16,"Animation"],[35,"Comedy"],[80,"Crime"],[99,"Documentary"],[18,"Drama"],[10751,"Family"],[14,"Fantasy"],[36,"History"],[27,"Horror"],[10402,"Music"],[9648,"Mystery"],[10749,"Romance"],[878,"Science Fiction"],[10770,"TV Movie"],[53,"Thriller"],[10752,"War"],[37,"Western"]]);
