/// <reference path="./IViewModel.d.ts" />

import { Genre, IMovieData } from "../lib/TMDB";

export default class ShelfData implements IViewModel<IMovieData> {
  readonly buffer = [
    {
      adult: false,
      backdrop_path: "/ulVUa2MvnJAjAeRt7h23FFJVRKH.jpg",
      cast: [
        {
          adult: false,
          cast_id: 5,
          character: "Nausicaä (voice)",
          credit_id: "52fe4215c3a36847f800281f",
          gender: 1,
          id: 613,
          known_for_department: "Acting",
          name: "Sumi Shimamoto",
          order: 0,
          original_name: "Sumi Shimamoto",
          popularity: 1.484,
          profile_path: "/bBA5xY4wrOUIpGnY6QPPQ9vNJB1.jpg",
        },
        {
          adult: false,
          cast_id: 9,
          character: "Mito (voice)",
          credit_id: "52fe4215c3a36847f800282f",
          gender: 2,
          id: 617,
          known_for_department: "Acting",
          name: "Ichirō Nagai",
          order: 1,
          original_name: "Ichirō Nagai",
          popularity: 1.513,
          profile_path: "/d5LuqwoIjMIqKvKmEk5y6AZY1Ww.jpg",
        },
        {
          adult: false,
          cast_id: 8,
          character: "Yupa (voice)",
          credit_id: "52fe4215c3a36847f800282b",
          gender: 2,
          id: 616,
          known_for_department: "Acting",
          name: "Gorō Naya",
          order: 2,
          original_name: "Gorō Naya",
          popularity: 1.176,
          profile_path: "/v5R3cjPEVeLRPWlZPziYP8ooV5w.jpg",
        },
        {
          adult: false,
          cast_id: 14,
          character: "Asbel (voice)",
          credit_id: "52fe4215c3a36847f8002843",
          gender: 2,
          id: 622,
          known_for_department: "Acting",
          name: "Yōji Matsuda",
          order: 3,
          original_name: "Yōji Matsuda",
          popularity: 0.6,
          profile_path: "/42WeHwCymsgJh3mLAyknCdRcef8.jpg",
        },
        {
          adult: false,
          cast_id: 16,
          character: "Kushana (voice)",
          credit_id: "52fe4215c3a36847f800284b",
          gender: 1,
          id: 624,
          known_for_department: "Acting",
          name: "Yoshiko Sakakibara",
          order: 4,
          original_name: "Yoshiko Sakakibara",
          popularity: 1.742,
          profile_path: "/jvApm6laePJ0dZzhwK5U73R9Bbx.jpg",
        },
        {
          adult: false,
          cast_id: 17,
          character: "Kurotowa (voice)",
          credit_id: "52fe4215c3a36847f800284f",
          gender: 2,
          id: 625,
          known_for_department: "Acting",
          name: "Iemasa Kayumi",
          order: 5,
          original_name: "Iemasa Kayumi",
          popularity: 2.161,
          profile_path: "/645IcH3dtGiZyMNq1i1041jVdyW.jpg",
        },
        {
          adult: false,
          cast_id: 7,
          character: "Oh-Baba (voice)",
          credit_id: "52fe4215c3a36847f8002827",
          gender: 1,
          id: 615,
          known_for_department: "Acting",
          name: "Hisako Kyouda",
          order: 6,
          original_name: "Hisako Kyouda",
          popularity: 0.753,
        },
        {
          adult: false,
          cast_id: 6,
          character: "Jihl (voice)",
          credit_id: "52fe4215c3a36847f8002823",
          gender: 0,
          id: 614,
          known_for_department: "Acting",
          name: "Mahito Tsujimura",
          order: 7,
          original_name: "Mahito Tsujimura",
          popularity: 0.6,
          profile_path: "/nB2XEl1ZZujLm8kNwNCAOrXBDlc.jpg",
        },
        {
          adult: false,
          cast_id: 15,
          character: "Lastel (voice)",
          credit_id: "52fe4215c3a36847f8002847",
          gender: 1,
          id: 623,
          known_for_department: "Acting",
          name: "Mina Tominaga",
          order: 8,
          original_name: "Mina Tominaga",
          popularity: 1.4,
          profile_path: "/hjuS06UcHyHc57TJe68zdeK13QL.jpg",
        },
        {
          adult: false,
          cast_id: 10,
          character: "Goru (voice)",
          credit_id: "52fe4215c3a36847f8002833",
          gender: 2,
          id: 618,
          known_for_department: "Acting",
          name: "Kōhei Miyauchi",
          order: 9,
          original_name: "Kōhei Miyauchi",
          popularity: 1.4,
          profile_path: "/ov1UMNf85T4ZFQSAN57KlcuTeDZ.jpg",
        },
        {
          adult: false,
          cast_id: 11,
          character: "Gikkuri (voice)",
          credit_id: "52fe4215c3a36847f8002837",
          gender: 2,
          id: 619,
          known_for_department: "Acting",
          name: "Jōji Yanami",
          order: 10,
          original_name: "Jōji Yanami",
          popularity: 1.619,
          profile_path: "/eO3PiUqjdzmAasku8QMv2eR45Lo.jpg",
        },
        {
          adult: false,
          cast_id: 12,
          character: "Niga (voice)",
          credit_id: "52fe4215c3a36847f800283b",
          gender: 2,
          id: 620,
          known_for_department: "Acting",
          name: "Minoru Yada",
          order: 11,
          original_name: "Minoru Yada",
          popularity: 0.6,
          profile_path: "/ssSVNGUgMD4ZwjEEYeZFzctDZ7k.jpg",
        },
        {
          adult: false,
          cast_id: 13,
          character: "Teto / Girl C (voice)",
          credit_id: "52fe4215c3a36847f800283f",
          gender: 1,
          id: 621,
          known_for_department: "Acting",
          name: "Rihoko Yoshida",
          order: 12,
          original_name: "Rihoko Yoshida",
          popularity: 0.6,
        },
        {
          adult: false,
          cast_id: 18,
          character: "Commando (voice)",
          credit_id: "52fe4215c3a36847f8002853",
          gender: 0,
          id: 626,
          known_for_department: "Acting",
          name: "Tetsuo Mizutori",
          order: 13,
          original_name: "Tetsuo Mizutori",
          popularity: 0.616,
        },
        {
          adult: false,
          cast_id: 54,
          character: "Girl A (voice)",
          credit_id: "5ada8459c3a36862d6001017",
          gender: 1,
          id: 1243597,
          known_for_department: "Acting",
          name: "Masako Sugaya",
          order: 14,
          original_name: "Masako Sugaya",
          popularity: 0.968,
        },
        {
          adult: false,
          cast_id: 55,
          character: "Girl B (voice)",
          credit_id: "5ada84819251410ad8000fc2",
          gender: 0,
          id: 1241776,
          known_for_department: "Acting",
          name: "Takako Sasuga",
          order: 15,
          original_name: "Takako Sasuga",
          popularity: 0.6,
        },
        {
          adult: false,
          cast_id: 56,
          character: "Boy A (voice)",
          credit_id: "5ada8496c3a36862ef001252",
          gender: 0,
          id: 55664,
          known_for_department: "Acting",
          name: "Chika Sakamoto",
          order: 16,
          original_name: "Chika Sakamoto",
          popularity: 1.582,
          profile_path: "/vuJylEz0fYajNdyiPop3TVbEVcD.jpg",
        },
        {
          adult: false,
          cast_id: 57,
          character: "Boy B (voice)",
          credit_id: "5ada84a60e0a261445001026",
          gender: 1,
          id: 100127,
          known_for_department: "Acting",
          name: "Tarako",
          order: 17,
          original_name: "Tarako",
          popularity: 2.158,
          profile_path: "/6f799bMbjXK1Ef7HFQyv6VPcgGE.jpg",
        },
        {
          adult: false,
          cast_id: 58,
          character: "Mayor of Pejite (voice)",
          credit_id: "5ada859ec3a36862c4001302",
          gender: 2,
          id: 217144,
          known_for_department: "Acting",
          name: "Mugihito",
          order: 18,
          original_name: "Mugihito",
          popularity: 1.22,
          profile_path: "/aAeRJLnOEtikBPN5V7bEAUfZ4Ak.jpg",
        },
        {
          adult: false,
          cast_id: 59,
          character: "Lastel's Mother (voice)",
          credit_id: "5ada85c79251410ac3001230",
          gender: 1,
          id: 1241584,
          known_for_department: "Acting",
          name: "Akiko Tsuboi",
          order: 19,
          original_name: "Akiko Tsuboi",
          popularity: 0.648,
        },
        {
          adult: false,
          cast_id: 60,
          character: "Pejite Citizen (voice)",
          credit_id: "5ada86570e0a261432001493",
          gender: 0,
          id: 1247301,
          known_for_department: "Acting",
          name: "Takeki Nakamura",
          order: 20,
          original_name: "Takeki Nakamura",
          popularity: 0.694,
        },
      ],
      cover: "https://image.tmdb.org/t/p/w500/muhyQAUn8RqMmXPVmBb8uaPtVXx.jpg",
      date: "2021-05-15T22:18:05.071Z",
      fav: false,
      genres: [Genre.Adventure, Genre.Animation, Genre.Fantasy],
      id: 81,
      info: "In einer fernen und bizarren, nur zuweilen der unseren noch recht ähnlichen Welt leben die letzten Überlebenden der Menschheit auf mit Sauerstoff versorgten Wüsteninseln, derweil den Rest des Planeten eine fremdartige, in ätzenden Stickstoff eingehüllte Pilzbotanik überwuchert, aus der heraus neue Tierarten zum Siegeszug über die Erde aufbrechen. Prinzessin Nausicaä ist bereit, diese Natur zu respektieren, die meisten ihrer Mitmenschen dagegen wollen die Pilzwälder vernichten. Ein Krieg der Arten ist die unausweichliche Folge.",
      mediaType: "movie",
      original: "風の谷のナウシカ",
      rating: 50,
      status: 0,
      title: "Nausicaä aus dem Tal der Winde",
      typ: 0,
      watchcount: 0,
    },
  ];

  *[Symbol.iterator]() {
    for (const el of this.buffer) {
      yield el;
    }
  }

  map<U>(
    callbackfn: (value: IMovieData, index: number, array: IMovieData[]) => U,
    thisArg?: any
  ): Array<U> {
    return this.buffer.map<U>(callbackfn, thisArg);
  }
}
